---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: petclinic-build
  namespace: demo5
spec:
  params:
    - name: APP_SOURCE_GIT
      type: string
      description: The application git repository
      default: https://github.com/siamaksade/spring-petclinic
    - name: APP_SOURCE_REVISION
      type: string
      description: The application git revision
      default: master
    - name: APP_MANIFESTS_GIT
      type: string
      description: The application manifests git repository
      default: https://github.com/siamaksade/spring-petclinic-config
    - name: APP_IMAGE_TAG
      type: string
      default: latest
      description: The application image tag to build
  workspaces:
  - name: workspace
  - name: maven-settings
  tasks:
  - name: source-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: workspace
    params:
    - name: url
      value: $(params.APP_SOURCE_GIT)
    - name: revision
      value: $(params.APP_SOURCE_REVISION)
    - name: depth
      value: "0"
    - name: subdirectory
      value: spring-petclinic
    - name: deleteExisting
      value: "true"
  - name: unit-tests
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - source-clone
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value: ["package", "-f", "spring-petclinic"]
  - name: code-analysis
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - unit-tests
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value:
      - install
      - sonar:sonar
      - -f
      - spring-petclinic
      - -Dsonar.host.url=http://sonarqube:9000
      - -Dsonar.userHome=/tmp/sonar
      - -DskipTests=true
  - name: security-scan
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - unit-tests
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value: ["--version", "-f", "spring-petclinic"]
  - name: release-app
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - code-analysis
      - security-scan
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value:
      - deploy
      - -f 
      - spring-petclinic
      - -DskipTests=true
      - -DaltDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-releases/
      - -DaltSnapshotDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-snapshots/
    workspaces:
    - name: workspace
      workspace: workspace