---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: repo5
  namespace: demo5
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: golang-test-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
             - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
  - name: repo-url
    value: https://github.com/manuelhepu/repo5.git