---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: repo5
  namespace: demo5
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: petclinic-build
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
             - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
  - name: repo-url
    value: repo5