---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: greeting
  namespace: demo2
spec:
  workspaces:
    - name: source
  params:
    - name: app-name
      type: string
      description: Name of the application
      default: demo

    - name: git-url
      type: string
      description: URL of the git repository containing application source code

    - name: git-revision
      type: string
      default: master
      description: Git revision to checkout application source code

    - name: image-url
      type: string
      description: Container image URL to publish
      default: demo

    - name: image-tag
      type: string
      default: latest
      description: Container image tag to publish


  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    - name: install-deps
      taskRef:
        name: npm
      runAfter: ['clone']
      workspaces:
        - name: source
          workspace: source
      params:
        - name: args
          value: ['ci', '--verbose', '--no-audit']

    - name: test
      taskRef:
        name: npm
      runAfter: ['install-deps']
      workspaces:
        - name: source
          workspace: source
      params:
        - name: args
          value: ['test']

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter: ['clone']
      workspaces:
        - name: source
          workspace: source
      params:
        - name: DOCKERFILE
          value: ./Containerfile
        - name: IMAGE
          value: $(params.image-url):$(params.image-tag)
