---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-test-pipeline
  namespace: demo2
spec:
  params:
  - name: repo-url
    type: string
  
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: clusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: run-build
      taskRef:
        name: golang-build
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: package
          value: github.com/chmouel/go-rest-api-test
        - name: packages
          value: "./"